/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface SpiAddform {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiAddformAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiAddquestion {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiAddquestionAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiAddrubrique {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiAddrubriqueAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface UniteenseignementAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface UniteenseignementAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiCreatee {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiCreateeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiEdit {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiEditAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiAddeval {
    'history': RouterHistory;
  }
  interface SpiAddevalAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHeadere {}
  interface SpiHeadereAttributes extends StencilHTMLAttributes {}

  interface SpiHeaderee {
    'history': RouterHistory;
  }
  interface SpiHeadereeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiList {}
  interface SpiListAttributes extends StencilHTMLAttributes {}

  interface SpiListens {}
  interface SpiListensAttributes extends StencilHTMLAttributes {}

  interface SpiEval {}
  interface SpiEvalAttributes extends StencilHTMLAttributes {}

  interface SpiRubrique {
    'match': MatchResults;
  }
  interface SpiRubriqueAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiLg {
    'history': RouterHistory;
  }
  interface SpiLgAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiProfile {}
  interface SpiProfileAttributes extends StencilHTMLAttributes {}

  interface SpiProfilenseignant {}
  interface SpiProfilenseignantAttributes extends StencilHTMLAttributes {}

  interface QualificatifAdd {}
  interface QualificatifAddAttributes extends StencilHTMLAttributes {}

  interface SpiQualificatif {}
  interface SpiQualificatifAttributes extends StencilHTMLAttributes {}

  interface SpiQualificatifens {}
  interface SpiQualificatifensAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}

  interface SpiUe {
    'match': MatchResults;
  }
  interface SpiUeAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiUeens {
    'match': MatchResults;
  }
  interface SpiUeensAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SpiAddform': Components.SpiAddform;
    'SpiAddquestion': Components.SpiAddquestion;
    'SpiAddrubrique': Components.SpiAddrubrique;
    'UniteenseignementAdd': Components.UniteenseignementAdd;
    'SpiCreatee': Components.SpiCreatee;
    'SpiEdit': Components.SpiEdit;
    'SpiAddeval': Components.SpiAddeval;
    'SpiHeader': Components.SpiHeader;
    'SpiHeadere': Components.SpiHeadere;
    'SpiHeaderee': Components.SpiHeaderee;
    'SpiHome': Components.SpiHome;
    'SpiList': Components.SpiList;
    'SpiListens': Components.SpiListens;
    'SpiEval': Components.SpiEval;
    'SpiRubrique': Components.SpiRubrique;
    'SpiLg': Components.SpiLg;
    'SpiProfile': Components.SpiProfile;
    'SpiProfilenseignant': Components.SpiProfilenseignant;
    'QualificatifAdd': Components.QualificatifAdd;
    'SpiQualificatif': Components.SpiQualificatif;
    'SpiQualificatifens': Components.SpiQualificatifens;
    'SpiRoot': Components.SpiRoot;
    'SpiUe': Components.SpiUe;
    'SpiUeens': Components.SpiUeens;
  }

  interface StencilIntrinsicElements {
    'spi-addform': Components.SpiAddformAttributes;
    'spi-addquestion': Components.SpiAddquestionAttributes;
    'spi-addrubrique': Components.SpiAddrubriqueAttributes;
    'uniteenseignement-add': Components.UniteenseignementAddAttributes;
    'spi-createe': Components.SpiCreateeAttributes;
    'spi-edit': Components.SpiEditAttributes;
    'spi-addeval': Components.SpiAddevalAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-headere': Components.SpiHeadereAttributes;
    'spi-headeree': Components.SpiHeadereeAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-list': Components.SpiListAttributes;
    'spi-listens': Components.SpiListensAttributes;
    'spi-eval': Components.SpiEvalAttributes;
    'spi-rubrique': Components.SpiRubriqueAttributes;
    'spi-lg': Components.SpiLgAttributes;
    'spi-profile': Components.SpiProfileAttributes;
    'spi-profilenseignant': Components.SpiProfilenseignantAttributes;
    'qualificatif-add': Components.QualificatifAddAttributes;
    'spi-qualificatif': Components.SpiQualificatifAttributes;
    'spi-qualificatifens': Components.SpiQualificatifensAttributes;
    'spi-root': Components.SpiRootAttributes;
    'spi-ue': Components.SpiUeAttributes;
    'spi-ueens': Components.SpiUeensAttributes;
  }


  interface HTMLSpiAddformElement extends Components.SpiAddform, HTMLStencilElement {}
  var HTMLSpiAddformElement: {
    prototype: HTMLSpiAddformElement;
    new (): HTMLSpiAddformElement;
  };

  interface HTMLSpiAddquestionElement extends Components.SpiAddquestion, HTMLStencilElement {}
  var HTMLSpiAddquestionElement: {
    prototype: HTMLSpiAddquestionElement;
    new (): HTMLSpiAddquestionElement;
  };

  interface HTMLSpiAddrubriqueElement extends Components.SpiAddrubrique, HTMLStencilElement {}
  var HTMLSpiAddrubriqueElement: {
    prototype: HTMLSpiAddrubriqueElement;
    new (): HTMLSpiAddrubriqueElement;
  };

  interface HTMLUniteenseignementAddElement extends Components.UniteenseignementAdd, HTMLStencilElement {}
  var HTMLUniteenseignementAddElement: {
    prototype: HTMLUniteenseignementAddElement;
    new (): HTMLUniteenseignementAddElement;
  };

  interface HTMLSpiCreateeElement extends Components.SpiCreatee, HTMLStencilElement {}
  var HTMLSpiCreateeElement: {
    prototype: HTMLSpiCreateeElement;
    new (): HTMLSpiCreateeElement;
  };

  interface HTMLSpiEditElement extends Components.SpiEdit, HTMLStencilElement {}
  var HTMLSpiEditElement: {
    prototype: HTMLSpiEditElement;
    new (): HTMLSpiEditElement;
  };

  interface HTMLSpiAddevalElement extends Components.SpiAddeval, HTMLStencilElement {}
  var HTMLSpiAddevalElement: {
    prototype: HTMLSpiAddevalElement;
    new (): HTMLSpiAddevalElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHeadereElement extends Components.SpiHeadere, HTMLStencilElement {}
  var HTMLSpiHeadereElement: {
    prototype: HTMLSpiHeadereElement;
    new (): HTMLSpiHeadereElement;
  };

  interface HTMLSpiHeadereeElement extends Components.SpiHeaderee, HTMLStencilElement {}
  var HTMLSpiHeadereeElement: {
    prototype: HTMLSpiHeadereeElement;
    new (): HTMLSpiHeadereeElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiListElement extends Components.SpiList, HTMLStencilElement {}
  var HTMLSpiListElement: {
    prototype: HTMLSpiListElement;
    new (): HTMLSpiListElement;
  };

  interface HTMLSpiListensElement extends Components.SpiListens, HTMLStencilElement {}
  var HTMLSpiListensElement: {
    prototype: HTMLSpiListensElement;
    new (): HTMLSpiListensElement;
  };

  interface HTMLSpiEvalElement extends Components.SpiEval, HTMLStencilElement {}
  var HTMLSpiEvalElement: {
    prototype: HTMLSpiEvalElement;
    new (): HTMLSpiEvalElement;
  };

  interface HTMLSpiRubriqueElement extends Components.SpiRubrique, HTMLStencilElement {}
  var HTMLSpiRubriqueElement: {
    prototype: HTMLSpiRubriqueElement;
    new (): HTMLSpiRubriqueElement;
  };

  interface HTMLSpiLgElement extends Components.SpiLg, HTMLStencilElement {}
  var HTMLSpiLgElement: {
    prototype: HTMLSpiLgElement;
    new (): HTMLSpiLgElement;
  };

  interface HTMLSpiProfileElement extends Components.SpiProfile, HTMLStencilElement {}
  var HTMLSpiProfileElement: {
    prototype: HTMLSpiProfileElement;
    new (): HTMLSpiProfileElement;
  };

  interface HTMLSpiProfilenseignantElement extends Components.SpiProfilenseignant, HTMLStencilElement {}
  var HTMLSpiProfilenseignantElement: {
    prototype: HTMLSpiProfilenseignantElement;
    new (): HTMLSpiProfilenseignantElement;
  };

  interface HTMLQualificatifAddElement extends Components.QualificatifAdd, HTMLStencilElement {}
  var HTMLQualificatifAddElement: {
    prototype: HTMLQualificatifAddElement;
    new (): HTMLQualificatifAddElement;
  };

  interface HTMLSpiQualificatifElement extends Components.SpiQualificatif, HTMLStencilElement {}
  var HTMLSpiQualificatifElement: {
    prototype: HTMLSpiQualificatifElement;
    new (): HTMLSpiQualificatifElement;
  };

  interface HTMLSpiQualificatifensElement extends Components.SpiQualificatifens, HTMLStencilElement {}
  var HTMLSpiQualificatifensElement: {
    prototype: HTMLSpiQualificatifensElement;
    new (): HTMLSpiQualificatifensElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLSpiUeElement extends Components.SpiUe, HTMLStencilElement {}
  var HTMLSpiUeElement: {
    prototype: HTMLSpiUeElement;
    new (): HTMLSpiUeElement;
  };

  interface HTMLSpiUeensElement extends Components.SpiUeens, HTMLStencilElement {}
  var HTMLSpiUeensElement: {
    prototype: HTMLSpiUeensElement;
    new (): HTMLSpiUeensElement;
  };

  interface HTMLElementTagNameMap {
    'spi-addform': HTMLSpiAddformElement
    'spi-addquestion': HTMLSpiAddquestionElement
    'spi-addrubrique': HTMLSpiAddrubriqueElement
    'uniteenseignement-add': HTMLUniteenseignementAddElement
    'spi-createe': HTMLSpiCreateeElement
    'spi-edit': HTMLSpiEditElement
    'spi-addeval': HTMLSpiAddevalElement
    'spi-header': HTMLSpiHeaderElement
    'spi-headere': HTMLSpiHeadereElement
    'spi-headeree': HTMLSpiHeadereeElement
    'spi-home': HTMLSpiHomeElement
    'spi-list': HTMLSpiListElement
    'spi-listens': HTMLSpiListensElement
    'spi-eval': HTMLSpiEvalElement
    'spi-rubrique': HTMLSpiRubriqueElement
    'spi-lg': HTMLSpiLgElement
    'spi-profile': HTMLSpiProfileElement
    'spi-profilenseignant': HTMLSpiProfilenseignantElement
    'qualificatif-add': HTMLQualificatifAddElement
    'spi-qualificatif': HTMLSpiQualificatifElement
    'spi-qualificatifens': HTMLSpiQualificatifensElement
    'spi-root': HTMLSpiRootElement
    'spi-ue': HTMLSpiUeElement
    'spi-ueens': HTMLSpiUeensElement
  }

  interface ElementTagNameMap {
    'spi-addform': HTMLSpiAddformElement;
    'spi-addquestion': HTMLSpiAddquestionElement;
    'spi-addrubrique': HTMLSpiAddrubriqueElement;
    'uniteenseignement-add': HTMLUniteenseignementAddElement;
    'spi-createe': HTMLSpiCreateeElement;
    'spi-edit': HTMLSpiEditElement;
    'spi-addeval': HTMLSpiAddevalElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-headere': HTMLSpiHeadereElement;
    'spi-headeree': HTMLSpiHeadereeElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-list': HTMLSpiListElement;
    'spi-listens': HTMLSpiListensElement;
    'spi-eval': HTMLSpiEvalElement;
    'spi-rubrique': HTMLSpiRubriqueElement;
    'spi-lg': HTMLSpiLgElement;
    'spi-profile': HTMLSpiProfileElement;
    'spi-profilenseignant': HTMLSpiProfilenseignantElement;
    'qualificatif-add': HTMLQualificatifAddElement;
    'spi-qualificatif': HTMLSpiQualificatifElement;
    'spi-qualificatifens': HTMLSpiQualificatifensElement;
    'spi-root': HTMLSpiRootElement;
    'spi-ue': HTMLSpiUeElement;
    'spi-ueens': HTMLSpiUeensElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
