/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';
import {
  Formation,
} from './global/formation';


export namespace Components {

  interface FormAdd {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface FormAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface FormForm {
    'formation': Formation;
    'history': RouterHistory;
    'isEditMode': boolean;
    'match': MatchResults;
  }
  interface FormFormAttributes extends StencilHTMLAttributes {
    'formation'?: Formation;
    'history'?: RouterHistory;
    'isEditMode'?: boolean;
    'match'?: MatchResults;
  }

  interface UniteenseignementAdd {
    'history': RouterHistory;
  }
  interface UniteenseignementAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiCreatee {
    'history': RouterHistory;
  }
  interface SpiCreateeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiEdit {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface SpiEditAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface SpiHeader {}
  interface SpiHeaderAttributes extends StencilHTMLAttributes {}

  interface SpiHeadere {}
  interface SpiHeadereAttributes extends StencilHTMLAttributes {}

  interface SpiHeaderee {
    'history': RouterHistory;
  }
  interface SpiHeadereeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiHome {}
  interface SpiHomeAttributes extends StencilHTMLAttributes {}

  interface SpiList {}
  interface SpiListAttributes extends StencilHTMLAttributes {}

  interface SpiListens {}
  interface SpiListensAttributes extends StencilHTMLAttributes {}

  interface SpiLg {
    'history': RouterHistory;
  }
  interface SpiLgAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiProfile {}
  interface SpiProfileAttributes extends StencilHTMLAttributes {}

  interface SpiProfilenseignant {}
  interface SpiProfilenseignantAttributes extends StencilHTMLAttributes {}

  interface QualificatifAdd {
    'history': RouterHistory;
  }
  interface QualificatifAddAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SpiQualificatif {}
  interface SpiQualificatifAttributes extends StencilHTMLAttributes {}

  interface SpiQualificatifens {}
  interface SpiQualificatifensAttributes extends StencilHTMLAttributes {}

  interface SpiRoot {}
  interface SpiRootAttributes extends StencilHTMLAttributes {}

  interface SpiTest {}
  interface SpiTestAttributes extends StencilHTMLAttributes {}

  interface SpiUe {
    'match': MatchResults;
  }
  interface SpiUeAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface SpiUeens {
    'match': MatchResults;
  }
  interface SpiUeensAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }
}

declare global {
  interface StencilElementInterfaces {
    'FormAdd': Components.FormAdd;
    'FormForm': Components.FormForm;
    'UniteenseignementAdd': Components.UniteenseignementAdd;
    'SpiCreatee': Components.SpiCreatee;
    'SpiEdit': Components.SpiEdit;
    'SpiHeader': Components.SpiHeader;
    'SpiHeadere': Components.SpiHeadere;
    'SpiHeaderee': Components.SpiHeaderee;
    'SpiHome': Components.SpiHome;
    'SpiList': Components.SpiList;
    'SpiListens': Components.SpiListens;
    'SpiLg': Components.SpiLg;
    'SpiProfile': Components.SpiProfile;
    'SpiProfilenseignant': Components.SpiProfilenseignant;
    'QualificatifAdd': Components.QualificatifAdd;
    'SpiQualificatif': Components.SpiQualificatif;
    'SpiQualificatifens': Components.SpiQualificatifens;
    'SpiRoot': Components.SpiRoot;
    'SpiTest': Components.SpiTest;
    'SpiUe': Components.SpiUe;
    'SpiUeens': Components.SpiUeens;
  }

  interface StencilIntrinsicElements {
    'form-add': Components.FormAddAttributes;
    'form-form': Components.FormFormAttributes;
    'uniteenseignement-add': Components.UniteenseignementAddAttributes;
    'spi-createe': Components.SpiCreateeAttributes;
    'spi-edit': Components.SpiEditAttributes;
    'spi-header': Components.SpiHeaderAttributes;
    'spi-headere': Components.SpiHeadereAttributes;
    'spi-headeree': Components.SpiHeadereeAttributes;
    'spi-home': Components.SpiHomeAttributes;
    'spi-list': Components.SpiListAttributes;
    'spi-listens': Components.SpiListensAttributes;
    'spi-lg': Components.SpiLgAttributes;
    'spi-profile': Components.SpiProfileAttributes;
    'spi-profilenseignant': Components.SpiProfilenseignantAttributes;
    'qualificatif-add': Components.QualificatifAddAttributes;
    'spi-qualificatif': Components.SpiQualificatifAttributes;
    'spi-qualificatifens': Components.SpiQualificatifensAttributes;
    'spi-root': Components.SpiRootAttributes;
    'spi-test': Components.SpiTestAttributes;
    'spi-ue': Components.SpiUeAttributes;
    'spi-ueens': Components.SpiUeensAttributes;
  }


  interface HTMLFormAddElement extends Components.FormAdd, HTMLStencilElement {}
  var HTMLFormAddElement: {
    prototype: HTMLFormAddElement;
    new (): HTMLFormAddElement;
  };

  interface HTMLFormFormElement extends Components.FormForm, HTMLStencilElement {}
  var HTMLFormFormElement: {
    prototype: HTMLFormFormElement;
    new (): HTMLFormFormElement;
  };

  interface HTMLUniteenseignementAddElement extends Components.UniteenseignementAdd, HTMLStencilElement {}
  var HTMLUniteenseignementAddElement: {
    prototype: HTMLUniteenseignementAddElement;
    new (): HTMLUniteenseignementAddElement;
  };

  interface HTMLSpiCreateeElement extends Components.SpiCreatee, HTMLStencilElement {}
  var HTMLSpiCreateeElement: {
    prototype: HTMLSpiCreateeElement;
    new (): HTMLSpiCreateeElement;
  };

  interface HTMLSpiEditElement extends Components.SpiEdit, HTMLStencilElement {}
  var HTMLSpiEditElement: {
    prototype: HTMLSpiEditElement;
    new (): HTMLSpiEditElement;
  };

  interface HTMLSpiHeaderElement extends Components.SpiHeader, HTMLStencilElement {}
  var HTMLSpiHeaderElement: {
    prototype: HTMLSpiHeaderElement;
    new (): HTMLSpiHeaderElement;
  };

  interface HTMLSpiHeadereElement extends Components.SpiHeadere, HTMLStencilElement {}
  var HTMLSpiHeadereElement: {
    prototype: HTMLSpiHeadereElement;
    new (): HTMLSpiHeadereElement;
  };

  interface HTMLSpiHeadereeElement extends Components.SpiHeaderee, HTMLStencilElement {}
  var HTMLSpiHeadereeElement: {
    prototype: HTMLSpiHeadereeElement;
    new (): HTMLSpiHeadereeElement;
  };

  interface HTMLSpiHomeElement extends Components.SpiHome, HTMLStencilElement {}
  var HTMLSpiHomeElement: {
    prototype: HTMLSpiHomeElement;
    new (): HTMLSpiHomeElement;
  };

  interface HTMLSpiListElement extends Components.SpiList, HTMLStencilElement {}
  var HTMLSpiListElement: {
    prototype: HTMLSpiListElement;
    new (): HTMLSpiListElement;
  };

  interface HTMLSpiListensElement extends Components.SpiListens, HTMLStencilElement {}
  var HTMLSpiListensElement: {
    prototype: HTMLSpiListensElement;
    new (): HTMLSpiListensElement;
  };

  interface HTMLSpiLgElement extends Components.SpiLg, HTMLStencilElement {}
  var HTMLSpiLgElement: {
    prototype: HTMLSpiLgElement;
    new (): HTMLSpiLgElement;
  };

  interface HTMLSpiProfileElement extends Components.SpiProfile, HTMLStencilElement {}
  var HTMLSpiProfileElement: {
    prototype: HTMLSpiProfileElement;
    new (): HTMLSpiProfileElement;
  };

  interface HTMLSpiProfilenseignantElement extends Components.SpiProfilenseignant, HTMLStencilElement {}
  var HTMLSpiProfilenseignantElement: {
    prototype: HTMLSpiProfilenseignantElement;
    new (): HTMLSpiProfilenseignantElement;
  };

  interface HTMLQualificatifAddElement extends Components.QualificatifAdd, HTMLStencilElement {}
  var HTMLQualificatifAddElement: {
    prototype: HTMLQualificatifAddElement;
    new (): HTMLQualificatifAddElement;
  };

  interface HTMLSpiQualificatifElement extends Components.SpiQualificatif, HTMLStencilElement {}
  var HTMLSpiQualificatifElement: {
    prototype: HTMLSpiQualificatifElement;
    new (): HTMLSpiQualificatifElement;
  };

  interface HTMLSpiQualificatifensElement extends Components.SpiQualificatifens, HTMLStencilElement {}
  var HTMLSpiQualificatifensElement: {
    prototype: HTMLSpiQualificatifensElement;
    new (): HTMLSpiQualificatifensElement;
  };

  interface HTMLSpiRootElement extends Components.SpiRoot, HTMLStencilElement {}
  var HTMLSpiRootElement: {
    prototype: HTMLSpiRootElement;
    new (): HTMLSpiRootElement;
  };

  interface HTMLSpiTestElement extends Components.SpiTest, HTMLStencilElement {}
  var HTMLSpiTestElement: {
    prototype: HTMLSpiTestElement;
    new (): HTMLSpiTestElement;
  };

  interface HTMLSpiUeElement extends Components.SpiUe, HTMLStencilElement {}
  var HTMLSpiUeElement: {
    prototype: HTMLSpiUeElement;
    new (): HTMLSpiUeElement;
  };

  interface HTMLSpiUeensElement extends Components.SpiUeens, HTMLStencilElement {}
  var HTMLSpiUeensElement: {
    prototype: HTMLSpiUeensElement;
    new (): HTMLSpiUeensElement;
  };

  interface HTMLElementTagNameMap {
    'form-add': HTMLFormAddElement
    'form-form': HTMLFormFormElement
    'uniteenseignement-add': HTMLUniteenseignementAddElement
    'spi-createe': HTMLSpiCreateeElement
    'spi-edit': HTMLSpiEditElement
    'spi-header': HTMLSpiHeaderElement
    'spi-headere': HTMLSpiHeadereElement
    'spi-headeree': HTMLSpiHeadereeElement
    'spi-home': HTMLSpiHomeElement
    'spi-list': HTMLSpiListElement
    'spi-listens': HTMLSpiListensElement
    'spi-lg': HTMLSpiLgElement
    'spi-profile': HTMLSpiProfileElement
    'spi-profilenseignant': HTMLSpiProfilenseignantElement
    'qualificatif-add': HTMLQualificatifAddElement
    'spi-qualificatif': HTMLSpiQualificatifElement
    'spi-qualificatifens': HTMLSpiQualificatifensElement
    'spi-root': HTMLSpiRootElement
    'spi-test': HTMLSpiTestElement
    'spi-ue': HTMLSpiUeElement
    'spi-ueens': HTMLSpiUeensElement
  }

  interface ElementTagNameMap {
    'form-add': HTMLFormAddElement;
    'form-form': HTMLFormFormElement;
    'uniteenseignement-add': HTMLUniteenseignementAddElement;
    'spi-createe': HTMLSpiCreateeElement;
    'spi-edit': HTMLSpiEditElement;
    'spi-header': HTMLSpiHeaderElement;
    'spi-headere': HTMLSpiHeadereElement;
    'spi-headeree': HTMLSpiHeadereeElement;
    'spi-home': HTMLSpiHomeElement;
    'spi-list': HTMLSpiListElement;
    'spi-listens': HTMLSpiListensElement;
    'spi-lg': HTMLSpiLgElement;
    'spi-profile': HTMLSpiProfileElement;
    'spi-profilenseignant': HTMLSpiProfilenseignantElement;
    'qualificatif-add': HTMLQualificatifAddElement;
    'spi-qualificatif': HTMLSpiQualificatifElement;
    'spi-qualificatifens': HTMLSpiQualificatifensElement;
    'spi-root': HTMLSpiRootElement;
    'spi-test': HTMLSpiTestElement;
    'spi-ue': HTMLSpiUeElement;
    'spi-ueens': HTMLSpiUeensElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
